-- SPDX-FileCopyrightText: Copyright 2026 Dmitry Marakasov <amdmi3@amdmi3.ru>
-- SPDX-License-Identifier: GPL-3.0-or-later

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE projects (
    name            TEXT NOT NULL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
	num_tasks		INTEGER NOT NULL DEFAULT 0,
	next_update_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
	last_updated_at TIMESTAMPTZ
);

CREATE INDEX projects_name_trgm ON projects USING gin (name gin_trgm_ops);
CREATE INDEX projects_queue_idx ON projects(next_update_at, name);

CREATE TABLE fetch_tasks (
	id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
	last_requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	project_name      TEXT NOT NULL REFERENCES projects(name),
	url               TEXT NOT NULL,
	variant           TEXT,
	version           TEXT
);

CREATE UNIQUE INDEX fetch_tasks_url_idx ON fetch_tasks(url);
