-- SPDX-FileCopyrightText: Copyright 2026 Dmitry Marakasov <amdmi3@amdmi3.ru>
-- SPDX-License-Identifier: GPL-3.0-or-later

CREATE TABLE items (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	text text NOT NULL,
	time timestamp with time zone NOT NULL DEFAULT now()
);
