-- SPDX-FileCopyrightText: Copyright 2026 Dmitry Marakasov <amdmi3@amdmi3.ru>
-- SPDX-License-Identifier: GPL-3.0-or-later

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE projects (
	-- metadata
	name            TEXT NOT NULL PRIMARY KEY,
	created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
	-- update status
	num_tasks       INTEGER NOT NULL DEFAULT 0,
	next_update_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
	last_updated_at TIMESTAMPTZ
);

CREATE INDEX projects_name_trgm ON projects USING gin (name gin_trgm_ops);
CREATE INDEX projects_queue_idx ON projects(next_update_at, name);

CREATE TABLE fetch_tasks (
	-- metadata
	id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
	-- identifiers
	url                     TEXT NOT NULL,
	project_name            TEXT NOT NULL REFERENCES projects(name),
	version                 TEXT NOT NULL,
	variant                 TEXT NOT NULL,
	-- fetch status
	num_attempts            INTEGER NOT NULL DEFAULT 0,
	next_fetch_attempt_at   TIMESTAMPTZ DEFAULT now(),
	last_fetch_attempted_at TIMESTAMPTZ,
	last_error              TEXT,
	log_id                  INTEGER
);

CREATE UNIQUE INDEX fetch_tasks_project_name_url_idx ON fetch_tasks(project_name, url);
CREATE UNIQUE INDEX fetch_tasks_queue_idx ON fetch_tasks(next_fetch_attempt_at, id) WHERE next_fetch_attempt_at IS NOT NULL;

CREATE TABLE logs (
	-- metadata
	id                    INTEGER PRIMARY KEY,
	fetch_task_id         INTEGER NOT NULL REFERENCES fetch_tasks(id) ON DELETE SET NULL,
	created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
	-- identifiers
	url                   TEXT NOT NULL,
	project_name          TEXT NOT NULL REFERENCES projects(name),
	version               TEXT NOT NULL,
	variant               TEXT NOT NULL,
	-- from fetch
	size                  INTEGER NOT NULL,
	last_modified         TIMESTAMPTZ,
	etag                  TEXT,
	-- from parse
	parsed_at             TIMESTAMPTZ,
	parser_version        INTEGER,
	parsed_num_lines      INTEGER,
	parsed_snippet_counts JSONB
);

CREATE INDEX logs_project_idx ON logs(project_name);
CREATE UNIQUE INDEX logs_parse_queue_idx ON logs(parser_version NULLS FIRST, id);
