CREATE TABLE versions (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    project_name       TEXT NOT NULL REFERENCES projects(name),
    version            TEXT NOT NULL,
    max_snippet_counts JSONB
);

CREATE UNIQUE INDEX versions_project_name_version_idx ON versions(project_name, version);
