CREATE TABLE warning_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL
);

CREATE UNIQUE INDEX warning_types_text_idx ON warning_types(text);

CREATE TABLE warning_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL
);

CREATE UNIQUE INDEX warning_messages_text_idx ON warning_messages(text);

ALTER TABLE snippets ADD COLUMN warning_type_id INTEGER REFERENCES warning_types(id);
CREATE INDEX snippets_warning_type_id_idx ON snippets(warning_type_id) WHERE warning_type_id IS NOT NULL;
ALTER TABLE snippets ADD COLUMN warning_message_id INTEGER REFERENCES warning_messages(id);
CREATE INDEX snippets_warning_message_id_idx ON snippets(warning_message_id) WHERE warning_message_id IS NOT NULL;
