name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
env:
  POSTGRESQL: 18
  RUSTFLAGS: -Dwarnings
  RUST: nightly-2026-07-06
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST }}
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-bin: "false"
      - name: Format check
        run: cargo fmt --check
      - name: Clippy check
        run: cargo clippy --all-targets
  build-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-bin: "false"
      - name: Set up PostgreSQL
        run: |
          sudo systemctl stop postgresql
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install postgresql-$POSTGRESQL
          sudo pg_createcluster $POSTGRESQL main
          sudo sed -i -e 's|5433|5432|' /etc/postgresql/$POSTGRESQL/main/postgresql.conf
          sudo sed -i -e '/^local/ s|peer|trust|' /etc/postgresql/$POSTGRESQL/main/pg_hba.conf
          sudo pg_ctlcluster $POSTGRESQL main start
      - name: Init the database
        run: |
          psql --username postgres -c "CREATE DATABASE wiyci"
          psql --username postgres -c "CREATE USER wiyci WITH PASSWORD 'wiyci'"
          psql --username postgres -c "GRANT ALL ON DATABASE wiyci TO wiyci"
      - name: Build as workspace
        run: cargo build
      # TODO: run in dry run mode, ensure it does not poll any sites
      #- name: Run the daemon
      #  run: |
      #    # only timeout is condidered success here, any early exit is a failure
      #    timeout 2s cargo run --bin wiyci-daemon -- --dsn postgresql://wiyci:wiyci@localhost/wiyci && exit 1 || [ $? -eq 124 ]
      - name: Run the webapp
        run: |
          # only timeout is condidered success here, any early exit is a failure
          timeout 2s cargo run --bin wiyci-web -- --dsn postgresql://wiyci:wiyci@localhost/wiyci --listen 127.0.0.1:3000 && exit 1 || [ $? -eq 124 ]
  build-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-bin: "false"
      - uses: taiki-e/install-action@cargo-hack
      - name: Build as individual crates
        run: cargo hack --workspace build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-bin: "false"
      - name: Set up PostgreSQL
        run: |
          sudo systemctl stop postgresql
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install postgresql-$POSTGRESQL
          sudo pg_createcluster $POSTGRESQL main
          sudo sed -i -e 's|5433|5432|' /etc/postgresql/$POSTGRESQL/main/postgresql.conf
          sudo sed -i -e '/^local/ s|peer|trust|' /etc/postgresql/$POSTGRESQL/main/pg_hba.conf
          sudo pg_ctlcluster $POSTGRESQL main start
      - name: Init the database
        run: |
          psql --username postgres -c "CREATE DATABASE wiyci"
          psql --username postgres -c "CREATE USER wiyci WITH PASSWORD 'wiyci'"
          psql --username postgres -c "GRANT ALL ON DATABASE wiyci TO wiyci"
      - name: Test
        run: cargo test
        env:
          DATABASE_URL: postgres:///?user=postgres
